### ISSUE TITLE
Any interest in a Steam Sprites + PS3 Backgrounds version of the patch?

### ISSUE THREAD

**Issue by jwgrlrrajn** [07th-mod/tatarigoroshi#21]
I recently modified a bunch of the Steam sprites to work in place of the PS3's daytime sensitive or zoomed versions of the sprites. Not sure if my edits would end up breaking anything, but is there any interest in giving users the option?

**Comment by drojf** [comment]
Well, if it's just an additional zip file which overwrites the existing sprites, I don't see the harm in that since we don't need to maintain anything. Is that how it will work?

**Comment by jwgrlrrajn** [comment]
Yes, that's basically how it would work.

**Comment by ItaloKnox** [comment]
I suggest you to open a repository with only the sprites uploaded. Leaving only a download link means that we're supporting that option and will solve all issues that might happen because of it. I have no problem in directing people to your work, we just can't take any more issues that aren't related to what we're directly working (PS3 graphics).

**Comment by drojf** [comment]
I thought this was the umineko github, sorry italo :S

**Comment by ItaloKnox** [comment]
Ahahaha, I thought your suggestion was fine, actually. It's only harder to update but if the creator sticks around there is no issue.

**Comment by jwgrlrrajn** [comment]
Just opened a repo for the Steam Sprites mod, so here's the link if you want to direct people to it then. :slightly_smiling_face: 

https://github.com/jwgrlrrajn/higurashi-tatarigoroshi_steam-sprite-mod

**Comment by ItaloKnox** [comment]
Cool, that's awesome. I'll update the wiki with your mod.
