### ISSUE TITLE
Missing sprites for Teppei

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#31]
While fixing the hellish tata_008 voices and other issues I also noticed that Hojo Teppei does not have any sprite when he appears. We should have his sprites from the PS3 right?

@Grelo This is your area, right? Can I ask you to add his sprites to the scripts?

**Comment by P-Chang** [comment]
[teppetest.zip](https://github.com/07th-mod/tatarigoroshi/files/1168811/teppetest.zip)
I made it. how do you think? 
It is still previous version(Jul 16, 2017 ), please back up.

it is only test so, it use low resolution graphic and high compressed.

**Comment by enumag** [comment]
@P-Chang Thanks for your effort but this is not how sprites should be added. It should be done with the `DrawBustshot` function. Or in this case probably better `DrawBustshotWithFiltering`. Sprites should not be part of the background.

**Comment by P-Chang** [comment]
I bit zoomed background because teppei is talking from window of second floor.
bg_059b is new file and there are no scene that use this image, so I put to teppei image on bg.

**Comment by enumag** [comment]
Oh I missed that fact. That's possibly why he doesn't have sprite in this case. Good that you pointed it out. Maybe we should leave it as it is.

**Comment by P-Chang** [comment]
[edited]
http://www.mediafire.com/file/pwxh4hj3xxuu5vr/graphics.rar

it is high resolution version and another image for meakashi effect fix.

compress please.

**Comment by Grelo** [comment]
@enumag He does not have any sprites in the PS3 version if i remember correctly. I will look into it, maybe im wrong. Maybe they are hiding his face on purpose so readers can feel the mystery surrounding him, idk.

Edit: 
Nope. No sprites, cgs or backgrounds with him in Tatari. :/

**Comment by enumag** [comment]
@Grelo There is a sprite in our Meakashi patch. I feel like we should see his face in Tata since Keiichi saw him.

![tetu_1_0](https://user-images.githubusercontent.com/539462/28531273-a7bd3f8e-7096-11e7-8973-4f1f12e8169b.png)

**Comment by Grelo** [comment]
@enumag 
I dont want to make changes that are not in either version, at least myself. If you mean sawing him when he was beating him then its true but there is just not enough sprites for him being surprised, in pain, scared etc. If someone can make these expressions then ok, but im backing out from it. Dont wanna be responsible for screwing this up or making inferior patch.

And i think they didnt add his sprite because readers could easily think that Keiichi had lost it and was hallucinating when they didnt find the body, which added to the mysteriousness.

**Comment by enumag** [comment]
@Grelo Alright, I'm convinced. :-)
