### ISSUE TITLE
Wrong translation?

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#41]
From the context I think the translation is slightly wrong [here](https://github.com/07th-mod/tatarigoroshi/blob/master/Update/tata_012.txt#L6567-L6568). I think it should rather be like this:

```
Coach seemed to realize he was treating me like a deviant when I raised my voice.
```

@ItaloKnox @DoctorDiablo Can you guys read the japanese text to confirm?

**Comment by ItaloKnox** [comment]
Hmm, it doesn't look wrong for me but definitely odd. Don't really get the context there.

**Comment by P-Chang** [comment]
you seem to be confused, because this sentence omits subjects.
Probably MG missed it with this reason.

Japanese text should be this in polite Japanese.
`"俺は"監督が半ば俺を異常者扱いしていることに気付き、"俺は"声を荒げてしまう`

If I translate it with my novice English.

`I realized coach was treating me like a deviant, so I raised my voice.`

**Comment by enumag** [comment]
@DoctorDiablo It seems we will need you to resolve this one. (Or @Norgus.)

**Comment by Norgus** [comment]
I agree with @P-Chang (sorry I'm not really working on the scripts but feel free to @ me or otherwise message questions)

**Comment by enumag** [comment]
@Norgus Thank you! :-)
