### ISSUE TITLE
small typo in Japanese start image

### ISSUE THREAD

**Issue by Norgus** [07th-mod/tatarigoroshi#55]
So I think there's a typo in the text in the file \CG\scenario_c_j.png

どのようは should be どのように

**Comment by ItaloKnox** [comment]
Shhh, I'm silently killing the bot.

**Comment by yagamisempai** [comment]
guys sorry i just want to tell you that i did a spanish tutorial about how to make your new lipsync patch to work, of course all credits and thanks goes to you guys for the greath work.
https://www.youtube.com/watch?v=CtQb8A1IfvI

thank you so much again for your great work and all this is posible because of you all thanks.

**Comment by enumag** [comment]
@Grelo Can you fix the scenario_c_j.png?

**Comment by Grelo** [comment]
@enumag Done. It is inside the issue with all scenarios.

Ok i put it below too:
![scenario_c_j](https://user-images.githubusercontent.com/22790067/37873029-361c74ce-3014-11e8-97f9-64c9a05831f4.png)

**Comment by enumag** [comment]
@ItaloKnox Do you want to change it in the CG pack or should I just commit it to the repo?

**Comment by ItaloKnox** [comment]
Commit it to the repo, please. It's always a pain to update Tata's CG pack.
