### ISSUE TITLE
Menu boxes not appearing

### ISSUE THREAD

**Issue by Ryptahi** [07th-mod/tatarigoroshi#65]
Installing the mod with mod patcher version 1.18 seems to make Tatarigoroshi unplayable. I patched the steam version of the game and used patcher on fresh install. Everything else seems to work fine, but I do not have any menu boxes available. Music only plays on background and only way to close the game is through task manager

**Comment by ItaloKnox** [comment]
Looks like the installer had some issues with the UI mod in your machine. Do you still have the installer log? It should be inside a folder called ``Logs``, in a .txt file. Just attach it to your next comment.

Meanwhile, I will take a look and see if there is anything wrong with it.

**Comment by ItaloKnox** [comment]
Oh, nevermind. We did some major changes in where the patch is installed and one little thing slipped by. It should be fixed now.

In case you still haven't fixed your game, just download this: https://07th-mod.com/rikachama/Tatarigoroshi-UI.7z

Thanks a lot!

**Comment by Ryptahi** [comment]
Thank you. That seemed to fix the problem. Seems like the installer did install everything correctly, but made shaderassets0.assets as .backup. So just removing the backup at end would result in working menu.

**Comment by ItaloKnox** [comment]
What actually happened is that the installer looks for a Steam dll to choose between Steam or DRM-free UI mods, but because we changed the folder where the installation happens, it was searching for the dll two folders above instead of the current folder. A simple change in the script fixed the issue. The backup is actually intended to save you from the trouble in case stuff like this happens. Give the UI mod another chance if you want! 👍 

Thanks for reporting this, it would take me some time to notice the mistake. Thankfully you already got your game to work properly so I will go ahead and close this issue.
