### ISSUE TITLE
Game won't save.

### ISSUE THREAD

**Issue by hokster1** [07th-mod/tatarigoroshi#74]
For some reason I can't click on the save button on the "Save & Load" screen and while playing the game, no matter how much I press F5 or click on the "Quick Save" button, I can't get back even if I press F7 or click on the "Quick Load" button. What am I supposed to do?
![higu3](https://user-images.githubusercontent.com/60367897/73217162-27344d80-4136-11ea-9694-7131607cff3c.png)

**Comment by ItaloKnox** [comment]
There is a chance you are having permission issues on Windows. Can you attach your ``output_log.txt`` file in your next comment? It should be inside the game folder, in ``HigurashiEp03_Data``.

**Comment by hokster1** [comment]
[output_log.txt](https://github.com/07th-mod/tatarigoroshi/files/4119656/output_log.txt)

**Comment by ItaloKnox** [comment]
The error below seems to pop up a little too often, but I think it's not related.

``Error: Cannot create FMOD::Sound instance for resource ¸tÀ<Í0×˜, (Operation could not be performed because specified sound/DSP connection is not ready. )``

Can you check if the unmodded game can save normally? It might also sound dumb, but sometimes a Windows reboot might fix the issue.

It should be also worth noting that you can disable the UI mod and see if it behaves differently in the modded game. Just go inside the ``HigurashiEp03_Data`` folder and rename your current ``sharedassets0.assets`` file to something else and rename the backup ``sharedassets0.assets.backup`` file to ``sharedassets0.assets``. This backup should exist if you installed the patch using our installer.

**Comment by enumag** [comment]
@hokster1 You can only save in the main story. Not in tips.
